# Generated by Django 5.0.1 on 2024-08-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PRMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pr_status', models.CharField(default='Raised', max_length=50)),
                ('PRDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasingDocumentHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_status', models.CharField(default='PO Created', max_length=100)),
                ('PORaisedDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='RFQMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_status', models.CharField(default='Pending', max_length=100)),
                ('StartingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='RFQSelectedSupplierHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_approval_status', models.CharField(default='Approval Pending', max_length=100)),
                ('StartingDate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchedulePOHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_status', models.CharField(default='Schedule Created', max_length=50)),
                ('ScheduleDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SupplierMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_status', models.CharField(default='Registered', max_length=50)),
            ],
        ),
    ]
